import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{ backgroundColor: "#00000077", padding: "10px" }}>
          <div style={{ color: "white", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <div>
              <img src="/icon.jpeg" alt="Logo" width={75} height={100} style={{ borderRadius: "100%", border: "1px solid white" }} />
            </div>
            <div style={{ display: "flex", gap: "10px" }}>
              <button style={{ border: "1px solid white", padding: "5px 10px", borderRadius: "5px" }}>Contatti</button>
              <button style={{ border: "1px solid white", padding: "5px 10px", borderRadius: "5px" }}>Cambia Lingua</button>
              <button style={{ border: "1px solid white", padding: "5px 10px", borderRadius: "5px" }}>Chi Sono</button>
            </div>
          </div>
        </header>
        {children}
        <footer style={{ backgroundColor: "#00000077", padding: "10px", textAlign: "center", marginTop: "20px", color : "white", position: 'absolute', bottom: '0', width: '100%' }}>
          <p>© 2025 Arturo Conti. Tutti i diritti riservati.</p>
        </footer>
      </body>
    </html>
  );
}
